services:

  backend:
    image: ramjeet500/lumina-backend:latest
    container_name: lumina_backend
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app

  frontend:
    image: ramjeet500/lumina-frontend:latest
    container_name: lumina_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:3000"
    networks:
      - app

networks:
  app:
