version: "3.9"

services:

  backend:
    build: ./backend
    container_name: lumina_backend
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "8000:8000"
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: lumina_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:3000"
    networks:
      - app

networks:
  app:
